### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5

### ISSUE THREAD

**Issue by CY12** [Hitomis/transferee#152]
recyclerview 只展示3个图片，3个item；填充transferee是全部的数据；
java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.hitomi.tilibrary.transfer.EmptyThumbState.getPlaceHolder(EmptyThumbState.java:126)
        at com.hitomi.tilibrary.transfer.EmptyThumbState.clipAndGetPlaceHolder(EmptyThumbState.java:144)
        at com.hitomi.tilibrary.transfer.EmptyThumbState.transferLoad(EmptyThumbState.java:58)
        at com.hitomi.tilibrary.transfer.TransferLayout.loadSourceView(TransferLayout.java:248)
        at com.hitomi.tilibrary.transfer.TransferLayout.loadSourceViewOffset(TransferLayout.java:237)
        at com.hitomi.tilibrary.transfer.TransferChangeListener.onPageSelected(TransferChangeListener.java:55)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:9328)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2564)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2250)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2452)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1749)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:872)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2405)
        at android.view.View.dispatchPointerEvent(View.java:9548)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4515)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4313)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3823)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3883)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3842)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3990)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3850)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4047)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3823)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3883)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3842)
    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImp

**Comment by wallyperry** [comment]
+1

**Comment by ITxiaoguang** [comment]
更多优化请看我这篇！！ https://github.com/ITxiaoguang/PhotoViewer
