### ISSUE TITLE
大量图片滚动crash

### ISSUE THREAD

**Issue by JarvanChen** [Hitomis/transferee#17]
里面有一个wrapOriginImageViewList，用来保存ImageView，如果有大量的Item呢，直接会Crash，能不能改成可见ImageView有动画，其他不可见的直接加载到ViewPager

**Comment by Hitomis** [comment]
目前重构版本已经初步完成。您可以 pull 下来进行使用，如有问题请提 Issues

**Comment by JarvanChen** [comment]
你好，作者，我看到回复立刻就pull下来了，我复制了大量的url图片地址，有50个左右吧，依然会crash呢


java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
                                                                              at com.hitomi.transferimage.activity.BaseActivity.wrapOriginImageViewList(BaseActivity.java:45)
                                                                              at com.hitomi.transferimage.activity.glide.GlideNoThumActivity.access$200(GlideNoThumActivity.java:19)
                                                                              at com.hitomi.transferimage.activity.glide.GlideNoThumActivity$NineGridAdapter$1.onClick(GlideNoThumActivity.java:88)

**Comment by Hitomis** [comment]
这个问题已经说过了
详见 [#20](https://github.com/Hitomis/transferee/issues/20)
