### ISSUE TITLE
RecyclerView多图片查看大图，快速左右滑动时崩溃

### ISSUE THREAD

**Issue by scrylove** [Hitomis/transferee#97]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@442fa0a
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
at android.widget.ImageView.onDraw(ImageView.java:1360)
at com.hitomi.tilibrary.view.image.TransferImage.onDraw(TransferImage.java:382)
at android.view.View.draw(View.java:20234)
at com.hitomi.tilibrary.view.image.PhotoView.draw(PhotoView.java:564)
at android.view.View.updateDisplayListIfDirty(View.java:19109)
at android.view.View.draw(View.java:19962)
at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
at android.view.View.updateDisplayListIfDirty(View.java:19100)
at android.view.View.draw

**Comment by Hitomis** [comment]
试了几个手机，都没有发现这个问题。
